### PR TITLE
feat: translate docs/docs/recipes/sourcing-data.md

### PR DESCRIPTION
**Pull request by k0mpreni**

### CODE REVIEW

**Review by dantereve — COMMENTED** [review]
Hello! This page was kinda big 😅.
I've noticed that you haven't translated a few lines between lines 70 and 200. Did you forget to commit something?

**Comment by k0mpreni** [comment]
Indeed it was a big page! 

Nice catch I don't know how I miss them, they should be translated now :)

**Review by dantereve — DISMISSED** [review]
Amazing job! Let’s merge this! 🔥

**Comment by k0mpreni** [comment]
Nice! I resolved the merge conflict

**Review by dantereve — APPROVED** [review]

**Pull request merged**
